### ISSUE TITLE
Unable to disbale expanding variables

### ISSUE THREAD

**Issue by xgouchet** [bitrise-steplib/bitrise-step-generate-text-file#1]
### Troubleshooting

- I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions. This is not mentionned anywhere!
- Which version of the step is effected? _0.1.0_
- Is the issue reproducible with the latest version? _YES_
- Does the issue happen sporadically, or every time? _EVERY TIME_
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? _YES_

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

I'm trying to generate a text file which contains a `$` symbol. Specifically, it contains a line with `url : "$rootDir/path/to/file"`. The `$rootDir` refers to a variable in my build toolchain and **NOT** a Bitrise environment variable.

There's no way to prevent expanding variable, and since there's no ENV variable with this name, `$rootDir` is replaced by an empty string. I've spent 3 days trying to debug a failing workflow before finding that the file is not generated the way I want it.

### Bitrise info

- Build URL: _Please share the build URL with us._
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: _YES / NO_
- Log: 

<details>
  <pre>
 
  </pre>
</details>

### Steps to reproduce

1. Create a workfwow with the following step: 
```
    - generate-text-file@0.1:
        inputs:
        - file_name: build.gradle
        - file_content: |-
            // Top-level build file where you can add configuration options common to all sub-projects/modules.
            buildscript {
                ext {
                    buildToolsVersion = "29.0.2"
                    minSdkVersion = 19
                    compileSdkVersion = 29
                    targetSdkVersion = 29
                }
                repositories {
                    google()
                    jcenter()
                }
                dependencies {
                    classpath("com.android.tools.build:gradle:3.5.3")
                    // NOTE: Do not place your application dependencies here; they belong
                    // in the individual module build.gradle files
                }
            }
            allprojects {
                repositories {
                    mavenLocal()
                    maven {
                        // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
                        url("$rootDir/../node_modules/react-native/android")
                    }
                    maven {
                        // Android JSC is installed from npm
                        url("$rootDir/../node_modules/jsc-android/dist")
                    }
                    google()
                    jcenter()
                    maven { url 'https://www.jitpack.io' }
                }
            }
        title: Generate build.gradle
```
2. Run with remote access
3. Once the file is generated, notice that the `$rootDir` are not written

**Comment by ofalvai** [comment]
Currently there is no way to disable expanding env vars in this step's inputs. I can think of a few workarounds though:

- Use a script step to create a file with the desired content
- Define a real env var on Bitrise named `rootDir` with the value of `$rootDir`. This way the expansion will produce the exact output you want.

**Comment by ofalvai** [comment]
@xgouchet you can define [additional options for each step input](https://devcenter.bitrise.io/bitrise-cli/step-inputs/), one of them is `is_expand`. You can disable expansion like this:

``` yaml
- generate-text-file@0.1:
        inputs:
        - file_name: build.gradle
        - file_content: ...
          opts:
            is_expand: false
```
